image: jelaniwoods/appdev2022-base-rails

tasks:
  - before: |
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9500-9999
    onOpen: ignore


vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
